### ISSUE TITLE
Compilation failed on M1 MacBook

### ISSUE THREAD

**Issue by neomsg-git** [signalapp/zkgroup#17]
### Platform
M1 MacBook

### Steps to reproduce
Compile the library:
`make libzkgroup`

### Error message
```
RUSTFLAGS='-C link-arg=-s' cargo build --release
info: syncing channel updates for '1.41.1-aarch64-apple-darwin'
info: latest update on 2020-02-27, rust version 1.41.1 (f3e1a954d 2020-02-24)
error: target 'aarch64-apple-darwin' not found in channel.  Perhaps check https://doc.rust-lang.org/nightly/rustc/platform-support.html for available targets
make: *** [libzkgroup] Error 1
```

**Comment by jrose-signal** [comment]
That sounds like you're trying to build an older tag; newer tags use a pinned nightly rustc rather than 1.41.1. Can you check your working directory to see what commit you're on?

**Comment by neomsg-git** [comment]
You are right! I was still working on version 0.7.0 and wasn't aware that this issue was already addressed from version 0.7.3 and onwards.
